spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 18041050561-qe3gb22avqrrb7qo0vn4e6c8carj909q.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email